version: '3.8'

services:
  app:
    build: .
    container_name: Search.Sherlock
    network_mode: "host"
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "7111:7111"